---
name: Build a release

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-freelinks

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.1

      - name: Build
        id: build
        run: |
          pnpm install
          pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          echo "TAG=$(git tag --sort version:refname | tail -n 1)" >> "$GITHUB_OUTPUT"

      - name: Upload ZIP file
        id: upload-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./${{ env.PLUGIN_NAME }}.zip
          asset_name: ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.TAG }}.zip
          overwrite: true

      - name: Upload main.js
        id: upload-main
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./main.js
          asset_name: main.js
          overwrite: true

      - name: Upload manifest.json
        id: upload-manifest
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./manifest.json
          asset_name: manifest.json
          overwrite: true
